# Generated by Django 5.2 on 2025-04-30 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bride', models.CharField(max_length=100)),
                ('groom', models.CharField(max_length=100)),
                ('religion', models.CharField(choices=[('Hinduism', 'Hinduism'), ('Islam', 'Islam'), ('Christianity', 'Christianity'), ('Sikhism', 'Sikhism'), ('Buddhism', 'Buddhism'), ('Jainism', 'Jainism'), ('Zoroastrianism', 'Zoroastrianism'), ('Judaism', 'Judaism'), ('Baháʼí Faith', 'Baháʼí Faith'), ('Tribal Religions', 'Tribal Religions'), ('Animism', 'Animism'), ('Atheism', 'Atheism'), ('Agnosticism', 'Agnosticism'), ('Non-religious', 'Non-religious'), ('Other', 'Other')], max_length=100)),
                ('caste', models.CharField(choices=[('Brahmin', 'Brahmin'), ('Kshatriya', 'Kshatriya'), ('Vaishya', 'Vaishya'), ('Kayastha', 'Kayastha'), ('Chettiar', 'Chettiar'), ('Kamma', 'Kamma'), ('Kapu', 'Kapu'), ('Mudaliar', 'Mudaliar'), ('Iyer', 'Iyer'), ('Iyengar', 'Iyengar'), ('Saraswat', 'Saraswat'), ('Maithil', 'Maithil'), ('Gaur', 'Gaur'), ('Rajput', 'Rajput'), ('Maratha', 'Maratha'), ('Reddy', 'Reddy'), ('Nair', 'Nair'), ('Agarwal', 'Agarwal'), ('Jain', 'Jain'), ('Komati', 'Komati'), ('Yadav', 'Yadav'), ('Kurmi', 'Kurmi'), ('Jat', 'Jat'), ('Gujjar', 'Gujjar'), ('Ezhava', 'Ezhava'), ('Vokkaliga', 'Vokkaliga'), ('Thevar', 'Thevar'), ('Mukkulathor', 'Mukkulathor'), ('Nadar', 'Nadar'), ('Vishwakarma', 'Vishwakarma'), ('Teli', 'Teli'), ('Kumhar', 'Kumhar'), ('Gounder', 'Gounder'), ('Ahir', 'Ahir'), ('Mehtar', 'Mehtar'), ('Chamar', 'Chamar'), ('Mahar', 'Mahar'), ('Paraiyar', 'Paraiyar'), ('Mala', 'Mala'), ('Madiga', 'Madiga'), ('Jatav', 'Jatav'), ('Dholi', 'Dholi'), ('Dom', 'Dom'), ('Valmiki', 'Valmiki'), ('Arunthathiyar', 'Arunthathiyar'), ('Pasi', 'Pasi'), ('Gond', 'Gond'), ('Bhil', 'Bhil'), ('Santhal', 'Santhal'), ('Oraon', 'Oraon'), ('Munda', 'Munda'), ('Khasi', 'Khasi'), ('Naga', 'Naga'), ('Bodo', 'Bodo'), ('Toda', 'Toda'), ('Nicobarese', 'Nicobarese'), ('Other', 'Other')], max_length=100)),
                ('wedding_date', models.DateField()),
                ('engagement_date', models.DateField(blank=True, null=True)),
                ('reception_date', models.DateField(blank=True, null=True)),
                ('wedding_venue', models.CharField(max_length=255)),
                ('engagement_venue', models.CharField(blank=True, max_length=255, null=True)),
                ('reception_venue', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_can_edit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_weddings', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_weddings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
